feat(test): improve test script
Add CLI functionality to test script

diff --git a/ci/test b/ci/test
--- a/ci/test
+++ b/ci/test
@@ -1,10 +1,75 @@
 #!/usr/bin/bash
 
-THIS_SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+# This helper script is used to run this repository's tests. It makes sure the tests are run
+# inside the docker container where the environment is set up. It also provides some options
+# to run specific tests or the full test suite.
 
-cd $THIS_SCRIPT_DIR/../environment
+# Exit immediately if a command exits with a non-zero status
+set -e
 
-docker compose run --rm --entrypoint="python3" notebook-cuda -m coverage run -m pytest --durations=0 -vs
-docker compose run --rm --entrypoint="python3" notebook-cuda -m coverage report --omit=/usr/local/*,/usr/lib/* -m 
+# Define default values for options
+RUN_FULL_SUITE=false
+RUN_TESTS=false
+SPECIFIC_TESTS=""
+
+function print_help {
+    echo "Usage: $0 [-f] [-t] [-s specific_tests]"
+    echo "Options:"
+    echo "  -f: Run full test suite. This will run all tests (including notebooks) and generate"
+    echo "      a coverage report"
+    echo "  -t: Run tests unit tests"
+    echo "  -s: Run specific tests. Use the tests' names as they appear in the pytest implementation"
+    echo "  -h: Print this help message"
+}
+
+while getopts "fthrs:" opt; do
+    case $opt in
+    f)
+        RUN_FULL_SUITE=true
+        ;;
+    t)
+        RUN_TESTS=true
+        ;;
+    s)
+        SPECIFIC_TESTS="$OPTARG"
+        ;;
+    \?)
+        print_help
+        exit 1
+        ;;
+    esac
+done
+
+# Check if no options are provided or if -h is provided, then print help and exit
+if [[ $OPTIND -eq 1 || "$1" == "-h" ]]; then
+    print_help
+    exit 0
+fi
+
+# Shift the options and arguments so that $1, $2, etc. contain the non-option arguments
+shift $((OPTIND - 1))
+
+# Get the directory of this script
+THIS_SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
+cd "$THIS_SCRIPT_DIR/../environment"
+
+if $RUN_FULL_SUITE; then
+    # Run full test suite if -f flag is set
+    docker compose run --rm --entrypoint="python3" notebook-cuda -m coverage run --source=. -m pytest --ignore=tmp --nbmake --durations=0 -vs
+    docker compose run --rm --entrypoint="python3" notebook-cuda -m coverage report --omit=/usr/local/*,/usr/lib/* -m
+    exit 0
+fi
+
+if $RUN_TESTS; then
+    # Run tests if -t flag is set
+    docker compose run --rm --entrypoint="python3" notebook-cuda -m pytest --durations=0 -vs
+    exit 0
+fi
+
+if [ -n "$SPECIFIC_TESTS" ]; then
+    # Run specific tests if -s flag is set
+    docker compose run --rm --entrypoint="python3" notebook-cuda -m pytest --durations=0 -vs -k "$SPECIFIC_TESTS"
+    exit 0
+fi
 
 cd -
